### ISSUE TITLE
Request for One-Shot Image Classification Code from your paper

### ISSUE THREAD

**Issue by TinaFan1020** [shihongl1998/LLM-as-a-blackbox-optimizer#1]
Hello, 
I'm reaching out regarding your paper, "Language Models as Black-Box Optimizers for Vision-Language Models", which I found incredibly insightful. I've been trying to replicate the one-shot image classification results using CLIP as outlined in your work, but I'm struggling to match the baseline scores reported.

I've thoroughly reviewed my code but can't seem to pinpoint the issue. Would it be possible for you to share the codebase or any pointers that might help me align my results with those presented in your paper? Any guidance or assistance you could provide would be immensely appreciated.

Thank you for your time and for the significant contributions your paper offers to the community.

**Comment by llm-can-optimize-vlm** [comment]
Thanks for your interests about our work! We will open source our code in the few weeks.

**Comment by shihongl1998** [comment]
Thanks for your interests about our work! We will open source our code in few weeks.
