### ISSUE TITLE
If the code of "Application: Text-to-Image Generation" is available?

### ISSUE THREAD

**Issue by SydCS** [shihongl1998/LLM-as-a-blackbox-optimizer#10]
Hi. Thank you for this good work.
I wonder if the code of "Application: Text-to-Image Generation" is available? 
More than grateful if you could release it.

**Comment by shihongl1998** [comment]
Hi SydCS,

Thanks for your interests about our work. I have attached a code snippet named as auto_prompt_image_optimization for your reference. Please feel free to change all the parameters and prompts based on your usage. Please let me know if you have any questions. 

Best,
Shihong
