### ISSUE TITLE
Few shot experiments code 

### ISSUE THREAD

**Issue by jmiemirza** [shihongl1998/LLM-as-a-blackbox-optimizer#8]
Hi, 

Nice work. Can you please provide the code for few-shot image classification experiments listed in the paper? 

Best, Mirza.

**Comment by shihongl1998** [comment]
Hi Mirza, 

Thanks for your interests on our work. I have updated with few-shot image classification experiments. 

Best,Shihong

**Comment by jmiemirza** [comment]
Hi, thank you. can you also please provide the LAIONCOCO_SELECTED templates? i cannot find the directory: './laion_coco_results/'. 

best, mirza
